# Starter pipeline
trigger:
- master

variables:
- group: Azure-Shifatullah-Variables



steps:
- powershell: echo $(azure-tenant)
- powershell: echo $env:TEST $env:AZURETENANT
  env:
    TEST: $(test)
    AZURETENANT: $(azure-tenant) 
- script: echo 'Hello, world! $(test) '
  displayName: 'Run a one-line script'

- task: PowerShell@2
  displayName: 'Provision Azure resources'
  inputs:
    targetType: 'filePath'
    filePath: 'Azure/PowerShell/ProvisionAzureResources.ps1' 
  env:
    TEST: $(test)
    AZURETENANT: $(azure-tenant)
    SHOESTOREID: $(shoestore-id)
    SHOESTORESECRET: $(shoestore-secret)