# Starter pipeline
trigger:
- master

variables:
- group: Azure-Shifatullah-Variables

steps:

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (3b9f2575-a5bf-4740-83da-d8f0efbd0613)'
    KeyVaultName: 'shoestore-vault'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: echo 'Hello, world! $(test)'
  displayName: 'Run a one-line script'

- task: PowerShell@2
  displayName: 'Provision Azure resources'
  inputs:
    targetType: 'filePath'
    filePath: 'Azure/PowerShell/ProvisionAzureResources.ps1'
    errorActionPreference: 'stop'