# Starter pipeline
trigger:
- master

variables:
- group: Azure-Shifatullah-Variables

steps:
- task: PowerShell@2
  displayName: 'Provision Azure resources'
  inputs:
    targetType: 'filePath'
    filePath: 'Azure/PowerShell/ProvisionAzureResources.ps1' 
  env:
    AZURETENANT: $(azure-tenant)
    SHOESTOREID: $(shoestore-id)
    SHOESTORESECRET: $(shoestore-secret)