# Starter pipeline
trigger:
- master

variables:
- group: Azure-Shifatullah-Variables
- name: one
  value: initialValue 

steps:
- powershell: echo $(one)
- script: echo 'Hello, world! $(one) '
  displayName: 'Run a one-line script'

- task: PowerShell@2
  displayName: 'Provision Azure resources'
  inputs:
    targetType: 'filePath'
    filePath: 'Azure/PowerShell/ProvisionAzureResources.ps1'
    errorActionPreference: 'stop'