# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- task: PowerShell@2
  displayName: 'Provision Azure resources'
  inputs:
    targetType: 'filePath'
    filePath: 'Azure/PowerShell/ProvisionAzureResources.ps1'
    errorActionPreference: 'stop'
  env:
    Test: $(test)
    AzureTenant: $(azure-tenant)
    ShoeStoreId: $(shoestore-id)
    ShoeStoreSecret: $(shoestore-secret)