# Starter pipeline
trigger:
- master

variables:
- group: Azure-Shifatullah-Variables

steps:
- script: echo 'Hello, world! $(test) '
  displayName: 'Run a one-line script'

- task: PowerShell@2
  displayName: 'Provision Azure resources'
  inputs:
    targetType: 'filePath'
    filePath: 'Azure/PowerShell/ProvisionAzureResources.ps1'
    errorActionPreference: 'stop'